# Custom Language File for Launcher Customizer

[ejs.app]
title = "ImperoMC Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU IMPEROMC LAUNCHER"
welcomeDescription = "Copyright © 2025 IMPEROMC"
welcomeDescCTA = ""
